// Generator for compiling Form Sections into raw HTML, CSS, and JS

export function generateFullHtml(sections = [], metaInfo = {}) {
  const { title = 'My Website', description = 'Built with HTML Studio', metaTags = '' } = metaInfo;
  const enabledSections = sections.filter(s => s.enabled);
  const sectionsHtml = enabledSections.map(section => renderSectionHtml(section)).join('\n\n');
  return `<!DOCTYPE html>\n<html lang="en" class="scroll-smooth">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${escapeHtml(title)}</title>\n  <meta name="description" content="${escapeHtml(description)}">\n  ${metaTags}\n  <script src="https://cdn.tailwindcss.com"></script>\n  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">\n  <link rel="stylesheet" href="styles.css">\n</head>\n<body class="bg-slate-50 text-slate-900 font-sans antialiased">\n${sectionsHtml}\n<script src="script.js"></script>\n</body>\n</html>`;
}

function buildGridSystemCss() {
  const spans = [];
  for (let i = 1; i <= 12; i++) spans.push(`.hs-col-${i} { grid-column: span ${i} / span ${i}; }`);
  const bp = (prefix, query) => {
    const rules = [];
    for (let i = 1; i <= 12; i++) rules.push(`  .hs-col-${prefix}-${i} { grid-column: span ${i} / span ${i}; }`);
    rules.push(`  .hs-col-${prefix}-offset-0 { grid-column-start: 1; }`);
    for (let i = 1; i <= 11; i++) rules.push(`  .hs-col-${prefix}-offset-${i} { grid-column-start: ${i + 1}; }`);
    return `@media (min-width: ${query}) {\n${rules.join('\n')}\n}`;
  };
  return `/* 12-column responsive grid - mobile first */\n*, *::before, *::after { box-sizing: border-box; }\nhtml { -webkit-text-size-adjust: 100%; text-size-adjust: 100%; }\nbody { margin: 0; overflow-x: hidden; }\nimg, video, canvas, svg { max-width: 100%; height: auto; display: block; }\n.hs-container { width: 100%; max-width: 72rem; margin-left: auto; margin-right: auto; padding-left: 1rem; padding-right: 1rem; }\n@media (min-width: 640px) { .hs-container { padding-left: 1.5rem; padding-right: 1.5rem; } }\n@media (min-width: 1024px) { .hs-container { padding-left: 2rem; padding-right: 2rem; } }\n.hs-row { display: grid; grid-template-columns: repeat(12, minmax(0, 1fr)); column-gap: 1rem; row-gap: 1.5rem; width: 100%; align-items: stretch; }\n@media (min-width: 640px) { .hs-row { column-gap: 1.5rem; row-gap: 1.75rem; } }\n@media (min-width: 1024px) { .hs-row { column-gap: 2rem; row-gap: 2rem; } }\n.hs-row > [class*="hs-col-"] { min-width: 0; max-width: 100%; }\n${spans.join('\n')}\n${bp('sm', '640px')}\n${bp('md', '768px')}\n${bp('lg', '1024px')}\n${bp('xl', '1280px')}\n.hs-row > *:not([class*="hs-col-"]) { grid-column: span 12 / span 12; min-width: 0; }\nbutton, a.hs-btn, .hs-btn { touch-action: manipulation; }\n@media (max-width: 639px) { .hs-stack-mobile { width: 100%; justify-content: stretch; } .hs-stack-mobile > a, .hs-stack-mobile > button { width: 100%; text-align: center; justify-content: center; } }\n`;
}

export function generateCss(sections = []) {
  let css = `/* Generated by HTML Studio */\n@layer base { body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; } }\n.gradient-bg { background: linear-gradient(135deg, rgba(79, 70, 229, 0.1) 0%, rgba(147, 51, 234, 0.15) 100%); }\n.glass-nav { backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); }\n${buildGridSystemCss()}\n`;
  sections.forEach((s) => {
    if (s.bgColor) css += `\n#${s.id} { background-color: ${s.bgColor}; }`;
    if (s.textColor) css += `\n#${s.id} { color: ${s.textColor}; }`;
  });
  return css;
}

export function generateJs(sections = []) {
  return `document.addEventListener('DOMContentLoaded', () => {\n  const mobileMenuBtn = document.getElementById('mobile-menu-btn');\n  const mobileMenu = document.getElementById('mobile-menu');\n  if (mobileMenuBtn && mobileMenu) {\n    mobileMenuBtn.addEventListener('click', () => {\n      const isOpen = mobileMenu.classList.toggle('hidden');\n      mobileMenuBtn.setAttribute('aria-expanded', String(!isOpen));\n    });\n  }\n  document.querySelectorAll('a[href^="#"]').forEach(anchor => {\n    anchor.addEventListener('click', function (e) {\n      const targetId = this.getAttribute('href');\n      if (targetId && targetId !== '#') {\n        const targetElement = document.querySelector(targetId);\n        if (targetElement) {\n          e.preventDefault();\n          targetElement.scrollIntoView({ behavior: 'smooth' });\n          if (mobileMenu && !mobileMenu.classList.contains('hidden')) {\n            mobileMenu.classList.add('hidden');\n            if (mobileMenuBtn) mobileMenuBtn.setAttribute('aria-expanded', 'false');\n          }\n        }\n      }\n    });\n  });\n  const contactForm = document.getElementById('contact-form');\n  if (contactForm) {\n    contactForm.addEventListener('submit', (e) => {\n      e.preventDefault();\n      alert('Thank you for your message! (Demo Form Submitted)');\n      contactForm.reset();\n    });\n  }\n});\n`;
}

function featureColClass(columns) {
  if (columns === 2) return 'hs-col-12 hs-col-md-6';
  if (columns === 4) return 'hs-col-12 hs-col-sm-6 hs-col-lg-3';
  return 'hs-col-12 hs-col-sm-6 hs-col-lg-4';
}

function escapeHtml(str = '') {
  return String(str).replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>').replace(/"/g, '"').replace(/'/g, '&#039;');
}

function getFontAwesomeIcon(iconName) {
  const map = { Sparkles: 'wand-magic-sparkles', Code: 'code', Zap: 'bolt', Rocket: 'rocket', Globe: 'globe', Shield: 'shield-halved', Cpu: 'microchip', Layers: 'layer-group', CheckCircle2: 'circle-check', Award: 'award', Smile: 'face-smile', Heart: 'heart', BarChart3: 'chart-column', Feather: 'feather', Clock: 'clock', Lock: 'lock', Send: 'paper-plane', Download: 'download' };
  return map[iconName] || 'cube';
}

function renderSectionHtml(section) {
  const { id, type } = section;
  const wrap = (inner) => inner;
  switch (type) {
    case 'header': {
      const { logoText, logoImage, sticky, navLinks = [], showCta, ctaText, ctaUrl, bgColor, textColor, accentColor } = section;
      return `<header id="${id}" class="${sticky ? 'sticky top-0 z-50' : 'relative'} shadow-sm border-b border-slate-200/50" style="background-color: ${bgColor || '#ffffff'}; color: ${textColor || '#1f2937'}">\n  <div class="hs-container"><div class="hs-row items-center" style="row-gap:0;">\n    <div class="hs-col-8 hs-col-md-3 flex items-center min-h-[4rem] sm:min-h-[5rem]"><a href="#" class="flex items-center space-x-3 text-lg sm:text-xl font-bold tracking-tight">${logoImage ? `<img src="${escapeHtml(logoImage)}" alt="Logo" class="h-8 w-auto">` : `<i class="fa-solid fa-cube text-2xl" style="color: ${accentColor || '#4f46e5'}"></i>`}<span>${escapeHtml(logoText || 'Brand')}</span></a></div>\n    <nav class="hs-col-6 hidden md:flex items-center justify-center space-x-6 lg:space-x-8 text-sm font-medium">${navLinks.map(link => `<a href="${escapeHtml(link.url)}" class="hover:opacity-75">${escapeHtml(link.label)}</a>`).join('')}</nav>\n    <div class="hs-col-4 hs-col-md-3 flex items-center justify-end space-x-3 min-h-[4rem] sm:min-h-[5rem]">${showCta ? `<a href="${escapeHtml(ctaUrl || '#')}" class="hidden sm:inline-flex items-center px-4 py-2 text-sm font-semibold rounded-lg text-white" style="background-color: ${accentColor || '#4f46e5'}">${escapeHtml(ctaText || 'Get Started')}</a>` : ''}<button id="mobile-menu-btn" type="button" class="md:hidden inline-flex items-center justify-center w-11 h-11 rounded-lg border border-slate-300" aria-label="Toggle menu" aria-expanded="false" aria-controls="mobile-menu"><i class="fa-solid fa-bars text-lg"></i></button></div>\n  </div></div>\n  <div id="mobile-menu" class="hidden md:hidden border-t border-slate-200/40"><div class="hs-container py-3 pb-5"><div class="hs-row" style="row-gap:0.25rem;">${navLinks.map(link => `<div class="hs-col-12"><a href="${escapeHtml(link.url)}" class="block text-base font-medium py-3">${escapeHtml(link.label)}</a></div>`).join('')}${showCta ? `<div class="hs-col-12 pt-2"><a href="${escapeHtml(ctaUrl || '#')}" class="inline-flex items-center justify-center w-full px-4 py-3 text-sm font-semibold rounded-lg text-white" style="background-color: ${accentColor || '#4f46e5'}">${escapeHtml(ctaText || 'Get Started')}</a></div>` : ''}</div></div></div>\n</header>`;
    }
    case 'hero': {
      const { badgeText, headline, subheadline, primaryCtaText, primaryCtaUrl, secondaryCtaText, secondaryCtaUrl, imageUrl, layout, bgColor, textColor, accentColor } = section;
      const isSideRight = layout === 'side-right';
      const isSideLeft = layout === 'side-left';
      const isSplit = isSideRight || isSideLeft;
      const imageCol = `<div class="hs-col-12 hs-col-lg-6"><div class="relative rounded-2xl overflow-hidden shadow-2xl border border-white/10"><img src="${escapeHtml(imageUrl || '')}" alt="Hero" class="w-full h-auto object-cover"></div></div>`;
      const copyCol = `<div class="hs-col-12 ${isSplit ? 'hs-col-lg-6' : 'hs-col-lg-10 hs-col-lg-offset-1'} ${isSplit ? '' : 'text-center'}"><div class="space-y-6">${badgeText ? `<div class="inline-flex items-center px-3.5 py-1.5 rounded-full text-xs font-semibold bg-white/10 border border-white/20">${escapeHtml(badgeText)}</div>` : ''}<h1 class="text-3xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-tight">${escapeHtml(headline || 'Welcome to Our Platform')}</h1><p class="text-base sm:text-lg lg:text-xl opacity-90 leading-relaxed">${escapeHtml(subheadline || 'Create amazing web experiences with ease.')}</p><div class="flex flex-col sm:flex-row flex-wrap gap-3 sm:gap-4 ${isSplit ? '' : 'justify-center'} pt-2 hs-stack-mobile">${primaryCtaText ? `<a href="${escapeHtml(primaryCtaUrl || '#')}" class="inline-flex items-center justify-center px-6 py-3.5 min-h-[48px] text-base font-semibold rounded-xl text-white shadow-lg" style="background-color: ${accentColor || '#6366f1'}">${escapeHtml(primaryCtaText)}</a>` : ''}${secondaryCtaText ? `<a href="${escapeHtml(secondaryCtaUrl || '#')}" class="inline-flex items-center justify-center px-6 py-3.5 min-h-[48px] text-base font-semibold rounded-xl border border-current/30">${escapeHtml(secondaryCtaText)}</a>` : ''}</div></div></div>`;
      return `<section id="${id}" class="py-12 sm:py-16 lg:py-24 overflow-hidden" style="background-color: ${bgColor || '#0f172a'}; color: ${textColor || '#f8fafc'}"><div class="hs-container"><div class="hs-row items-center">${isSideLeft && imageUrl ? imageCol : ''}${copyCol}${isSideRight && imageUrl ? imageCol : ''}</div></div></section>`;
    }
    case 'features': {
      const { title, subtitle, items = [], columns = 3, bgColor, cardBgColor, textColor, accentColor } = section;
      const colClass = featureColClass(columns);
      return `<section id="${id}" class="py-12 sm:py-16 lg:py-24" style="background-color: ${bgColor || '#f8fafc'}; color: ${textColor || '#0f172a'}"><div class="hs-container"><div class="hs-row mb-8 sm:mb-12 lg:mb-16"><div class="hs-col-12 hs-col-lg-8 hs-col-lg-offset-2 text-center space-y-4"><h2 class="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight">${escapeHtml(title || 'Features')}</h2>${subtitle ? `<p class="text-base sm:text-lg opacity-80">${escapeHtml(subtitle)}</p>` : ''}</div></div><div class="hs-row">${items.map(item => `<div class="${colClass}"><div class="h-full p-6 sm:p-8 rounded-2xl shadow-sm border border-slate-200/80" style="background-color: ${cardBgColor || '#ffffff'}"><div class="w-12 h-12 rounded-xl flex items-center justify-center mb-6 text-white text-xl" style="background-color: ${accentColor || '#4f46e5'}"><i class="fa-solid fa-${getFontAwesomeIcon(item.icon)}"></i></div><h3 class="text-lg sm:text-xl font-bold mb-3">${escapeHtml(item.title)}</h3><p class="opacity-80 text-sm leading-relaxed">${escapeHtml(item.description)}</p></div></div>`).join('\n')}</div></div></section>`;
    }
    case 'about': {
      const { title, subtitle, storyText, imageUrl, stats = [], bgColor, textColor, accentColor } = section;
      return `<section id="${id}" class="py-12 sm:py-16 lg:py-24" style="background-color: ${bgColor || '#ffffff'}; color: ${textColor || '#1f2937'}"><div class="hs-container"><div class="hs-row items-center">${imageUrl ? `<div class="hs-col-12 hs-col-lg-6"><div class="relative rounded-2xl overflow-hidden shadow-xl"><img src="${escapeHtml(imageUrl)}" alt="About" class="w-full h-auto object-cover"></div></div>` : ''}<div class="hs-col-12 ${imageUrl ? 'hs-col-lg-6' : 'hs-col-lg-10 hs-col-lg-offset-1'}"><div class="space-y-6">${subtitle ? `<span class="text-sm font-semibold uppercase tracking-wider" style="color: ${accentColor || '#4f46e5'}">${escapeHtml(subtitle)}</span>` : ''}<h2 class="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight">${escapeHtml(title || 'About Us')}</h2><p class="text-base sm:text-lg opacity-90 leading-relaxed whitespace-pre-line">${escapeHtml(storyText || '')}</p>${stats.length > 0 ? `<div class="hs-row pt-6 border-t border-slate-200/50">${stats.map(s => `<div class="hs-col-6 hs-col-sm-3"><div class="text-2xl sm:text-3xl font-extrabold" style="color: ${accentColor || '#4f46e5'}">${escapeHtml(s.number)}</div><div class="text-xs sm:text-sm opacity-75 font-medium mt-1">${escapeHtml(s.label)}</div></div>`).join('')}</div>` : ''}</div></div></div></div></section>`;
    }
    case 'testimonials': {
      const { title, subtitle, items = [], bgColor, cardBgColor, textColor, accentColor } = section;
      const n = items.length;
      const colClass = n === 1 ? 'hs-col-12 hs-col-lg-8 hs-col-lg-offset-2' : n === 2 ? 'hs-col-12 hs-col-md-6' : 'hs-col-12 hs-col-md-6 hs-col-lg-4';
      return `<section id="${id}" class="py-12 sm:py-16 lg:py-24" style="background-color: ${bgColor || '#0f172a'}; color: ${textColor || '#f8fafc'}"><div class="hs-container"><div class="hs-row mb-8 sm:mb-12 lg:mb-16"><div class="hs-col-12 hs-col-lg-8 hs-col-lg-offset-2 text-center space-y-4"><h2 class="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight">${escapeHtml(title || 'Testimonials')}</h2>${subtitle ? `<p class="text-base sm:text-lg opacity-80">${escapeHtml(subtitle)}</p>` : ''}</div></div><div class="hs-row">${items.map(t => `<div class="${colClass}"><div class="h-full p-6 sm:p-8 rounded-2xl shadow-md border border-white/10 flex flex-col justify-between space-y-6" style="background-color: ${cardBgColor || '#1e293b'}"><div class="space-y-4"><div class="flex text-amber-400 space-x-1">${Array.from({ length: t.rating || 5 }).map(() => `<i class="fa-solid fa-star text-sm"></i>`).join('')}</div><p class="opacity-90 italic text-sm leading-relaxed">"${escapeHtml(t.quote)}"</p></div><div class="flex items-center space-x-4 pt-4 border-t border-white/10">${t.avatar ? `<img src="${escapeHtml(t.avatar)}" alt="${escapeHtml(t.author || '')}" class="w-11 h-11 rounded-full object-cover">` : `<div class="w-11 h-11 rounded-full flex items-center justify-center font-bold text-white" style="background-color: ${accentColor || '#4f46e5'}">${escapeHtml((t.author || 'U')[0])}</div>`}<div><div class="font-bold text-sm">${escapeHtml(t.author)}</div><div class="text-xs opacity-70">${escapeHtml(t.role)}</div></div></div></div></div>`).join('\n')}</div></div></section>`;
    }
    case 'pricing': {
      const { title, subtitle, tiers = [], bgColor, cardBgColor, textColor, accentColor } = section;
      const n = tiers.length;
      const colClass = n === 1 ? 'hs-col-12 hs-col-md-8 hs-col-md-offset-2 hs-col-lg-6 hs-col-lg-offset-3' : n === 2 ? 'hs-col-12 hs-col-md-6' : n === 4 ? 'hs-col-12 hs-col-sm-6 hs-col-lg-3' : 'hs-col-12 hs-col-md-6 hs-col-lg-4';
      return `<section id="${id}" class="py-12 sm:py-16 lg:py-24" style="background-color: ${bgColor || '#f8fafc'}; color: ${textColor || '#0f172a'}"><div class="hs-container"><div class="hs-row mb-8 sm:mb-12 lg:mb-16"><div class="hs-col-12 hs-col-lg-8 hs-col-lg-offset-2 text-center space-y-4"><h2 class="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight">${escapeHtml(title || 'Pricing')}</h2>${subtitle ? `<p class="text-base sm:text-lg opacity-80">${escapeHtml(subtitle)}</p>` : ''}</div></div><div class="hs-row items-stretch">${tiers.map(t => `<div class="${colClass}"><div class="relative h-full p-6 sm:p-8 rounded-2xl border ${t.isPopular ? 'ring-2 shadow-xl md:scale-[1.03]' : 'border-slate-200 shadow-sm'} flex flex-col justify-between" style="background-color: ${cardBgColor || '#ffffff'}; ${t.isPopular ? `border-color: ${accentColor || '#4f46e5'}` : ''}">${t.isPopular ? `<div class="absolute -top-3.5 left-1/2 transform -translate-x-1/2 px-4 py-1 rounded-full text-xs font-bold uppercase tracking-wider text-white" style="background-color: ${accentColor || '#4f46e5'}">Most Popular</div>` : ''}<div class="space-y-6"><h3 class="text-xl sm:text-2xl font-bold">${escapeHtml(t.name)}</h3><p class="text-xs opacity-75">${escapeHtml(t.description || '')}</p><div class="flex items-baseline flex-wrap"><span class="text-3xl sm:text-4xl font-extrabold tracking-tight">${escapeHtml(t.price)}</span><span class="text-sm opacity-75 ml-1">${escapeHtml(t.period)}</span></div><ul class="space-y-3 pt-4 border-t border-slate-200/60 text-sm">${(t.features || []).map(f => `<li class="flex items-start space-x-3"><i class="fa-solid fa-check text-emerald-500 mt-0.5"></i><span>${escapeHtml(f)}</span></li>`).join('')}</ul></div><div class="pt-8"><a href="${escapeHtml(t.buttonUrl || '#')}" class="block text-center w-full py-3 px-4 min-h-[48px] rounded-xl font-semibold ${t.isPopular ? 'text-white' : 'border border-current/30'}" style="${t.isPopular ? `background-color: ${accentColor || '#4f46e5'}` : ''}">${escapeHtml(t.buttonText || 'Choose Plan')}</a></div></div></div>`).join('\n')}</div></div></section>`;
    }
    case 'contact': {
      const { title, subtitle, email, phone, address, submitButtonText, bgColor, textColor, accentColor } = section;
      return `<section id="${id}" class="py-12 sm:py-16 lg:py-24" style="background-color: ${bgColor || '#ffffff'}; color: ${textColor || '#1f2937'}"><div class="hs-container"><div class="hs-row"><div class="hs-col-12 hs-col-lg-5"><div class="space-y-8"><div><h2 class="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight mb-3">${escapeHtml(title || 'Contact Us')}</h2>${subtitle ? `<p class="text-base sm:text-lg opacity-80">${escapeHtml(subtitle)}</p>` : ''}</div><div class="space-y-6 text-sm sm:text-base">${email ? `<div class="flex items-center space-x-4"><div class="w-10 h-10 shrink-0 rounded-lg flex items-center justify-center text-white" style="background-color: ${accentColor || '#4f46e5'}"><i class="fa-solid fa-envelope"></i></div><div class="min-w-0"><div class="font-semibold text-xs opacity-65">Email</div><div class="break-all">${escapeHtml(email)}</div></div></div>` : ''}${phone ? `<div class="flex items-center space-x-4"><div class="w-10 h-10 shrink-0 rounded-lg flex items-center justify-center text-white" style="background-color: ${accentColor || '#4f46e5'}"><i class="fa-solid fa-phone"></i></div><div class="min-w-0"><div class="font-semibold text-xs opacity-65">Phone</div><div>${escapeHtml(phone)}</div></div></div>` : ''}${address ? `<div class="flex items-center space-x-4"><div class="w-10 h-10 shrink-0 rounded-lg flex items-center justify-center text-white" style="background-color: ${accentColor || '#4f46e5'}"><i class="fa-solid fa-location-dot"></i></div><div class="min-w-0"><div class="font-semibold text-xs opacity-65">Location</div><div>${escapeHtml(address)}</div></div></div>` : ''}</div></div></div><div class="hs-col-12 hs-col-lg-7"><form id="contact-form" class="p-5 sm:p-8 rounded-2xl shadow-lg border border-slate-200/80 space-y-5 bg-white text-slate-900"><div class="hs-row" style="row-gap:1.25rem;"><div class="hs-col-12 hs-col-sm-6"><label class="block text-sm font-semibold mb-2">Full Name</label><input type="text" required class="w-full px-4 py-3 min-h-[48px] rounded-xl border border-slate-300 bg-slate-50 outline-none" placeholder="John Doe"></div><div class="hs-col-12 hs-col-sm-6"><label class="block text-sm font-semibold mb-2">Email Address</label><input type="email" required class="w-full px-4 py-3 min-h-[48px] rounded-xl border border-slate-300 bg-slate-50 outline-none" placeholder="john@example.com"></div><div class="hs-col-12"><label class="block text-sm font-semibold mb-2">Message</label><textarea rows="4" required class="w-full px-4 py-3 rounded-xl border border-slate-300 bg-slate-50 outline-none" placeholder="How can we help you?"></textarea></div><div class="hs-col-12"><button type="submit" class="w-full py-3.5 px-6 min-h-[48px] rounded-xl font-semibold text-white" style="background-color: ${accentColor || '#4f46e5'}">${escapeHtml(submitButtonText || 'Send Message')}</button></div></div></form></div></div></div></section>`;
    }
    case 'footer': {
      const { brandName, tagline, copyright, columns = [], socialLinks = {}, bgColor, textColor } = section;
      const linkColClass = 'hs-col-6 hs-col-md-3';
      return `<footer id="${id}" class="py-10 sm:py-16 border-t border-slate-800" style="background-color: ${bgColor || '#0f172a'}; color: ${textColor || '#94a3b8'}"><div class="hs-container"><div class="hs-row pb-10 sm:pb-12 border-b border-slate-800"><div class="hs-col-12 hs-col-md-6 space-y-4"><h3 class="text-xl font-bold text-white">${escapeHtml(brandName || 'Brand')}</h3><p class="text-sm max-w-sm leading-relaxed opacity-80">${escapeHtml(tagline || '')}</p><div class="flex flex-wrap gap-4 pt-2">${socialLinks.twitter ? `<a href="${escapeHtml(socialLinks.twitter)}" class="hover:text-white inline-flex w-11 h-11 items-center justify-center" aria-label="Twitter"><i class="fa-brands fa-x-twitter text-lg"></i></a>` : ''}${socialLinks.github ? `<a href="${escapeHtml(socialLinks.github)}" class="hover:text-white inline-flex w-11 h-11 items-center justify-center" aria-label="GitHub"><i class="fa-brands fa-github text-lg"></i></a>` : ''}${socialLinks.linkedin ? `<a href="${escapeHtml(socialLinks.linkedin)}" class="hover:text-white inline-flex w-11 h-11 items-center justify-center" aria-label="LinkedIn"><i class="fa-brands fa-linkedin text-lg"></i></a>` : ''}${socialLinks.discord ? `<a href="${escapeHtml(socialLinks.discord)}" class="hover:text-white inline-flex w-11 h-11 items-center justify-center" aria-label="Discord"><i class="fa-brands fa-discord text-lg"></i></a>` : ''}</div></div>${columns.map(col => `<div class="${linkColClass}"><h4 class="text-sm font-semibold uppercase tracking-wider text-white mb-4">${escapeHtml(col.title)}</h4><ul class="space-y-2.5 text-sm">${(col.links || []).map(l => `<li><a href="${escapeHtml(l.url)}" class="hover:text-white">${escapeHtml(l.label)}</a></li>`).join('')}</ul></div>`).join('')}</div><div class="hs-row pt-8 text-xs opacity-70"><div class="hs-col-12 hs-col-sm-6 text-center sm:text-left">${escapeHtml(copyright || '')}</div><div class="hs-col-12 hs-col-sm-6 text-center sm:text-right">Powered by HTML Studio</div></div></div></footer>`;
    }
    case 'custom': {
      const { rawHtml, bgColor, textColor } = section;
      return `<section id="${id}" class="py-8 sm:py-12" style="background-color: ${bgColor || '#ffffff'}; color: ${textColor || '#1f2937'}"><div class="hs-container"><div class="hs-row"><div class="hs-col-12">${rawHtml || '<!-- Custom HTML Block — use .hs-row / .hs-col-* for a 12-column layout -->'}</div></div></div></section>`;
    }
    default:
      return `<section id="${id}" class="py-8"><div class="hs-container"><div class="hs-row"><div class="hs-col-12">Section ${id}</div></div></div></section>`;
  }
}

export function buildStandaloneHtml(html = '', css = '', js = '', metaInfo = {}) {
  const title = metaInfo.title || 'Website';
  let doc = String(html || '').trim();
  const safeCss = String(css || '').replace(/<\/style/gi, '<\\/style');
  const safeJs = String(js || '').replace(/<\/script/gi, '<\\/script');
  if (!doc) {
    doc = `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${escapeHtml(title)}</title>\n</head>\n<body></body>\n</html>`;
  }
  if (!/^<!doctype/i.test(doc) && !/<html[\s>]/i.test(doc)) {
    doc = `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${escapeHtml(title)}</title>\n</head>\n<body>\n${doc}\n</body>\n</html>`;
  }
  if (!/^<!doctype/i.test(doc)) doc = '<!DOCTYPE html>\n' + doc;
  const styleBlock = safeCss ? `<style id="html-studio-css">\n${safeCss}\n</style>` : '';
  const scriptBlock = safeJs ? `<script id="html-studio-js">\n${safeJs}\n</script>` : '';
  if (styleBlock) {
    if (/<link[^>]*href=["'](?:\.\/)?styles\.css["'][^>]*>/i.test(doc)) doc = doc.replace(/<link[^>]*href=["'](?:\.\/)?styles\.css["'][^>]*>/i, styleBlock);
    else if (!/id=["']html-studio-css["']/.test(doc)) {
      if (/<\/head>/i.test(doc)) doc = doc.replace(/<\/head>/i, `  ${styleBlock}\n</head>`);
      else doc = styleBlock + '\n' + doc;
    }
  }
  if (scriptBlock) {
    if (/<script[^>]*src=["'](?:\.\/)?script\.js["'][^>]*>\s*<\/script>/i.test(doc)) doc = doc.replace(/<script[^>]*src=["'](?:\.\/)?script\.js["'][^>]*>\s*<\/script>/i, scriptBlock);
    else if (!/id=["']html-studio-js["']/.test(doc)) {
      if (/<\/body>/i.test(doc)) doc = doc.replace(/<\/body>/i, `  ${scriptBlock}\n</body>`);
      else doc = doc + '\n' + scriptBlock;
    }
  }
  return doc;
}
